FROM paraview-builder:ubuntu20 AS builder

ARG GRID_EXTRACTOR_PLUGIN_PATH=gep/gridextractorplugin

# paraview build options
ENV PARALLEL_NB=4
ENV PVSB_GIT_TAG="v5.13.0"
ENV RENDERING_BACKEND="EGL"
ENV ENABLE="-DENABLE_hdf5=ON"
ENV USE_SYSTEM="-DUSE_SYSTEM_hdf5=ON -DUSE_SYSTEM_zlib=ON"

# build paraview
RUN /work/build.bash

# total stuff specific dependencies
RUN apt update && apt install -y libboost-all-dev sqlite3 libxml2-dev libfreetype-dev

ENV FESPP_BUILD_ROOT_DIR=/work/ttl

COPY ./fespp/build_scripts/build-fesapi-dependencies.sh /root/build-fesapi-dependencies.sh
COPY ./fespp/build_scripts/build-fespp.sh /root/build-fespp.sh
COPY ./fespp/build_scripts/build.sh /root/build.sh

# build total stuff
RUN bash /root/build.sh

RUN mkdir /work/ttl/gep
ENV GEP_BUILD_ROOT_DIR=/work/ttl/gep

# build grid extractor plugin
COPY $GRID_EXTRACTOR_PLUGIN_PATH /work/ttl/gep/gridextractorplugin
COPY ./gep/build_scripts/build.sh /root/build-gep.sh

RUN bash /root/build-gep.sh

FROM nvidia/opengl:1.2-glvnd-devel-ubuntu22.04 AS runtime

RUN apt-get update && \
  apt-get install -y \
  python3.10 \
  python3.10-distutils \
  # python-is-python3 creates a symlink for python to python3
  python-is-python3 \
  # For creating virtual environments
  python3.10-venv && \
  rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y libhdf5-103 libosmesa6-dev

COPY --from=builder /work/pvsb-build/install /opt/paraview
COPY --from=builder /work/ttl /work/ttl

ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1
WORKDIR /wish_root

RUN adduser -u 5678 --disabled-password --gecos "" appuser && chown -R appuser /wish_root
USER appuser

ENTRYPOINT ["/opt/paraview/bin/pvpython", \
  "-m", "wish_wells_viewer", \
  "--host", "0.0.0.0", \
  "--venv", "/wish_root/wish_venv", \
  "--server", \
  "--port", "1234", \
  "--fespp-plugin-path", "/work/ttl/build-fespp/lib/paraview-5.13/plugins/Fespp/Fespp.so", \
  "--local-epc-file-path", "/wish_root/data/PETREL_IJK/PETREL_OLYMPUS_TRAME.epc", \
  "--remote-epc-file-location", "http://localhost:2222/PETREL_IJK/PETREL_OLYMPUS_TRAME.epc", \
  "--remote-h5-file-location", "http://localhost:2222/PETREL_IJK/PETREL_OLYMPUS_TRAME.h5", \
  "--slicing-plugin-path", "/work/ttl/gep/build-gep/lib/paraview-5.13/plugins/GridExtractorPlugin/GridExtractorPlugin.so"]
